version: 2.1

orbs:
  helm: circleci/helm@0.1.2
  gcp-cli: circleci/gcp-cli@1.8.2

jobs:
  build-chart:
    parameters:
      chart:
        type: string
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - helm/install-helm-client
      - run:
          name: Lint
          command: helm lint << parameters.chart >>
      - run:
          name: Package
          command: |
            mkdir charts
            helm package << parameters.chart >> -d ./charts
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./charts
  push-helm-repository:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - helm/install-helm-client
      - gcp-cli/initialize
      - run:
          name: Install helm-gcs
          command: helm plugin install https://github.com/hayorov/helm-gcs --version 0.2.2
      - run:
          name: Add Repo, Auth and push Repo
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
            helm repo add request-gcs gs://request-charts
            for f in ./charts/*; do echo $f; helm gcs push $f request-gcs --public --force ; done;

workflows:
  version: 2
  build:
    jobs:
      - build-chart:
          name: build-request-node
          chart: request-node
      - build-chart:
          name: build-eth-watch
          chart: eth-watch
      - build-chart:
          name: build-api-sync
          chart: api-sync
      - push-helm-repository:
          requires:
            - build-request-node
            - build-eth-watch
            - build-api-sync
          filters:
            branches:
              only:
                - master
