apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  REQUEST_COLLECTION_NAME: {{ .Values.db.collection | quote }}
  DATABASE_HOST: {{ required ".Values.db.host is required" .Values.db.host }}
  DATABASE_PORT: {{ .Values.db.port | quote }}
  DATABASE_USER: {{ .Values.db.username  | quote }}
  DATABASE_PASSWORD: {{ .Values.db.password  | quote }}
  DATABASE_NAME: {{ required ".Values.db.name is required" .Values.db.name  | quote }}
  GOOGLE_PUBSUB_SUBSCRIPTION: {{ .Values.pubsub.subscription | quote }}
  GOOGLE_PROJECT_ID: {{ .Values.pubsub.googleProjectId | quote }}
  SENDGRID_APIKEY: {{ .Values.sendgridApiKey | quote }}
  REQUEST_NODE_URL_LIVE: {{ required ".Values.node.live is required" .Values.node.live }}
  REQUEST_NODE_URL_TEST: {{ required ".Values.node.test is required" .Values.node.test }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 2 }}
{{- end }}