# Default values for request-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The number of replicas for the Request Node
replicaCount: 1

nodeEnv:
  # Required settings
  # the mnemonic of a wallet for gas fees
  mnemonic:
  # the URL of the Web3 provider (infura for instance)
  web3ProviderUrl:
  # the ethereum network (0 custom, 1 mainnet, 4 rinkeby)
  networkId:

  # other settings
  logLevel: DEBUG
  initializationStorageFilePath: "/index/store.json"

  # extra environment variables
  extra:
  # - name: VAR_NAME
  #   value: VAR_VALUE

# The index storage directory on the node. Should match the initializationStorageFilePath path
nodeIndexDirectoryPath: /index

# The Request Node image information
nodeImage:
  image: requestnetwork/request-node
  tag: latest
  pullPolicy: Always

# The IPFS image information
ipfsImage:
  image: requestnetwork/request-ipfs
  tag: latest
  pullPolicy: Always

# Name override
nameOverride: ""
fullnameOverride: ""

# The request node service type and port
service:
  type: ClusterIP
  port: 80

# The resources declaration for the Request Node and IPFS
resources:
  node: {}
  ipfs: {}

# Request Node port
port: 3000

# IPFS swarm and API ports
ipfsSwarmPort: 4001
ipfsApiPort: 5001

# The Request Node and IPFS persistence settings
persistence:
  # Disable if we don't want persistence
  enabled: true
  node:
    ## request node data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    size: "8Gi"
    accessModes:
      - ReadWriteOnce
  ipfs:
    ## ipfs data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    size: "8Gi"
    accessModes:
      - ReadWriteOnce

# Advanced kubernetes configs
nodeSelector: {}
tolerations: []
affinity: {}
