apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "request-node.fullname" . }}
  labels:
{{ include "request-node.labels" . | indent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "request-node.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "request-node.labels" . | indent 8 }}
    spec:
      securityContext:
        # The image runs as uid 1000 by default, and needs to be able to write to the persistent volume to be able to start.
        fsGroup: 1000
        # Shorten the time it takes to change ownership and permission of files on boot.
        fsGroupChangePolicy: "OnRootMismatch"
        runAsUser: 1000

      containers:
      # Request Node Container
      - name: {{ .Chart.Name }}
        image: "{{ .Values.nodeImage.image }}:{{ .Values.nodeImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.nodeImage.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - /usr/bin/wget
              - --no-verbose
              - --tries=1
              - --spider
              - http://localhost:{{ .Values.port }}/healthz
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        startupProbe:
          exec:
            command:
              - /usr/bin/wget
              - --no-verbose
              - --tries=1
              - --spider
              - http://localhost:{{ .Values.port }}/readyz
          periodSeconds: {{ .Values.startupProbe.periodSeconds}}
          failureThreshold: {{ .Values.startupProbe.failureThreshold}}
        resources:
          {{- toYaml .Values.resources.node | nindent 12 }}
        volumeMounts:
        - name: persistent-index
          mountPath: {{ .Values.nodeIndexDirectoryPath }}
        env:
          - name: MNEMONIC
            valueFrom:
              secretKeyRef:
                name: {{ include "request-node.fullname" . }}-secret
                key: mnemonic
          - name: WEB3_PROVIDER_URL
            value: {{ required "nodeEnv.web3ProviderUrl is required" .Values.nodeEnv.web3ProviderUrl }}
          - name: PORT
            value: {{ .Values.port | quote }}
          - name: ETHEREUM_NETWORK_ID
            value: {{ required "nodeEnv.networkId is required" .Values.nodeEnv.networkId | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.nodeEnv.logLevel }}
          {{- if not .Values.ipfs.sidecar }}
          - name: IPFS_URL
            value: {{ required "ipfs.api.url is required when IPFS is not a sidecar" .Values.ipfs.api.url | quote }}
          {{- end }}
          - name: INITIALIZATION_STORAGE_FILE_PATH
            value: {{ .Values.nodeEnv.initializationStorageFilePath }}
        {{- with .Values.nodeEnv.extra -}}
          {{- toYaml . | nindent 10 }}
        {{- end -}}

      {{ if .Values.ipfs.sidecar }}
      # IPFS Node Container
      - name: ipfs
        image: "{{ .Values.ipfs.image.image }}:{{ .Values.ipfs.image.tag }}"
        imagePullPolicy: {{ .Values.ipfs.image.pullPolicy }}
        livenessProbe:
          tcpSocket:
            port: swarm
          initialDelaySeconds: {{ .Values.ipfs.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ipfs.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ipfs.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.ipfs.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.ipfs.livenessProbe.failureThreshold }}
        readinessProbe:
          tcpSocket:
            port: swarm
          initialDelaySeconds: {{ .Values.ipfs.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ipfs.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ipfs.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.ipfs.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.ipfs.readinessProbe.failureThreshold }}
        ports:
        - containerPort: {{ .Values.ipfs.swarm.port }}
          name: swarm
        - containerPort: {{ .Values.ipfs.api.port }}
          name: api
        volumeMounts:
        - name: ipfs-storage
          mountPath: /data/ipfs
        env:
        # Forces the IPFS node to connect to the Request dedicated network
        - name: LIBP2P_FORCE_PNET
          value: "1"
        {{- if .Values.ipfs.swarm.externalIP }}
        - name: EXTERNAL_IP
          value: {{ .Values.ipfs.swarm.externalIP }}
        {{- end }}
        {{- if .Values.ipfs.swarm.port }}
        - name: SWARM_PORT
          value: {{ .Values.ipfs.swarm.port | quote }}
        {{- end }}
        {{- if .Values.ipfs.identity }}
        - name: PEER_ID
          value: {{ .Values.ipfs.identity.peerId | quote }}
        - name: PRIVATE_KEY
          valueFrom:
              secretKeyRef:
                name: {{ include "request-node.fullname" . }}-secret
                key: ipfsPrivateKey
        {{- end }}
        {{- range $key, $value := .Values.ipfs.extraEnv }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources.ipfs | nindent 12 }}

      {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- /* If persistence is disabled, we use temporary volumes for IPFS and the Request Node persistent index */}}
      {{- if not .Values.persistence.enabled }}
      volumes:
      {{- if .Values.ipfs.sidecar  }}
      - name: ipfs-storage
        emptyDir: {}
      {{- end }}
      - name: persistent-index
        emptyDir: {}
      {{- end }}

  {{- /* If persistence is enabled (default), we create a persistent volume for the Request Node persistent index and one for IPFS */}}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  {{- if .Values.ipfs.sidecar  }}
  # IPFS storage volume
  - metadata:
      name: ipfs-storage
      labels:
        app.kubernetes.io/name: {{ include "request-node.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- range $key, $value := .Values.persistence.ipfs.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
    spec:
      accessModes:
        {{- range .Values.persistence.ipfs.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.ipfs.size | quote }}
    {{- if .Values.persistence.ipfs.storageClass }}
    {{- if (eq "-" .Values.persistence.ipfs.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.ipfs.storageClass }}"
    {{- end }}
    {{- end }}
  {{- end}}
  # Request node persistent index volume
  - metadata:
      name: persistent-index
      labels:
        app.kubernetes.io/name: {{ include "request-node.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- range $key, $value := .Values.persistence.node.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
    spec:
      accessModes:
        {{- range .Values.persistence.node.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.node.size | quote }}
    {{- if .Values.persistence.node.storageClass }}
    {{- if (eq "-" .Values.persistence.node.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.node.storageClass }}"
    {{- end }}
    {{- end }}
  {{- end }}
