apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-node.fullname" . }}-secret
  labels:
{{ include "request-node.labels" . | indent 4 }}
type: Opaque
data:
  mnemonic: {{ required "mnemonic is required" .Values.nodeEnv.mnemonic | b64enc }}
  {{- if .Values.ipfs.identity }}
  ipfsPrivateKey: {{ .Values.ipfs.identity.privateKey | b64enc }}
  {{- end }}