# Default values for request-ipfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The number of replicas for the Request Node
replicaCount: 1

# Name override
nameOverride: ""
fullnameOverride: ""

# The resources declaration for the IPFS node
resources: {}

# The IPFS image information
image:
  image: requestnetwork/request-ipfs
  pullPolicy: IfNotPresent
  # defaults to Chart.AppVersion
  # tag:
# IPFS swarm port
swarm:
  port: 4001
  loadBalancerIP:
# IPFS API port
api:
  port: 5001
  # The ipfs API service type and port
  service:
    type: ClusterIP
    port: 5001

# The Request Node and IPFS persistence settings
persistence:
  ## ipfs data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  size: "8Gi"
  accessModes:
    - ReadWriteOnce

livenessProbe: {}

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 3

# Advanced kubernetes configs
nodeSelector: {}
tolerations: []
affinity: {}
