{{- if .Values.identity }}
{{- if .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "request-ipfs.fullname" . }}-secret
  labels:
{{ include "request-ipfs.labels" . | indent 4 }}
spec:
  encryptedData:
    ipfsPrivateKey: {{ .Values.identity.privateKey }}
{{- else}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-ipfs.fullname" . }}-secret
  labels:
{{ include "request-ipfs.labels" . | indent 4 }}
type: Opaque
data:
  ipfsPrivateKey: {{ .Values.identity.privateKey | b64enc }}
{{- end }}
{{- end }}
