apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  REQUEST_COLLECTION_NAME: {{ .Values.db.collection | quote }}
  DATABASE_HOST: {{ .Values.db.host | quote }}
  DATABASE_PORT: {{ .Values.db.port | quote }}
  DATABASE_USER: {{ .Values.db.username  | quote }}
  DATABASE_PASSWORD: {{ .Values.db.password  | quote }}
  DATABASE_NAME: {{ .Values.db.name  | quote }}
  WEB3_URL: {{ .Values.web3Url | quote }}
  NETWORK: {{ .Values.network }}
  IPFS_HOST: {{ .Values.ipfs.host | quote }}
  IPFS_PORT: {{ .Values.ipfs.port | quote }}
  IPFS_TIMEOUT: {{ .Values.ipfs.timeout | quote }}
  GOOGLE_PUBSUB_TOPIC: {{ .Values.pubsub.topic | quote }}
  HEALTHCHECK_URL: {{ .Values.healthcheck | quote }}
  FREQUENCY : {{ .Values.frequency | quote  }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 2 }}
{{- end }}