{{- if .Values.identity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-ipfs.fullname" . }}-secret
  labels:
{{ include "request-ipfs.labels" . | indent 4 }}
type: Opaque
data:
  ipfsPrivateKey: {{ .Values.identity.privateKey | b64enc }}
{{- end }}