# Load balancer to expose the IPFS node swarm port
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "request-node.labels" . | indent 4 }}
  name: {{ include "request-node.fullname" . }}-ipfs
spec:
  ports:
  - name: swarm
    port: {{ .Values.ipfsSwarmPort }}
    protocol: TCP
    targetPort: 4001
  selector:
{{ include "request-node.labels" . | indent 4 }}
  sessionAffinity: None
  type: LoadBalancer