image:
  repository: eth-watch
  tag: latest
  registry: eu.gcr.io/request-240714

redis:
 # required
 host: "" 
 port: 6379

db: 
 # required
 host: "" 
 # required
 name: "" 
 port: 27017
 collection: "requests"
 username: ""
 password: ""

# required
web3Url: "" 
# required: mainnet, rinkeby
network: "" 
erc20Hash: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef


replicas: 1
resources: {}