image:
  repository: eth-watch
  tag: latest
  registry: eu.gcr.io/request-240714

db:
  # required
  host: ''
  # required
  name: ''
  port: 27017
  collection: 'requests'
  username: ''
  password: ''

ipfs:
  #required
  host: ''
  port: 5001
  timeout: 3000

pubsub:
  # required
  credentialsSecretName: ''
  credentialsFileName: credentials.json
  # optional, defaults to api-sync
  # topic:

# required
web3Url: ''
# required: mainnet, rinkeby
network: ''
# optional, the run frequency. Defaults to 5000
# frequency:
# optional, the healtchecks.io URL.
# healthcheck:

replicas: 1
resources: {}
