image:
  repository: eth-watch
  tag: latest
  registry: eu.gcr.io/request-240714

db:
  # required
  host: ''
  # required
  name: ''
  port: 27017
  collection: 'requests'
  username: ''
  password: ''

ipfs:
  #required
  host: ''
  port: 5001
  timeout: 3000

pubsub:
  # required
  credentialsSecretName: ''
  credentialsFileName: credentials.json
  topic: api-sync

# required
web3Url: ''
# required: mainnet, rinkeby
network: ''
# the run frequency
frequency: 5000
# optional, the healtchecks.io URL.
healthcheck: ""

replicas: 1
resources: {}
