image:
  repository: api-sync
  tag: latest
  registry: eu.gcr.io/request-240714

db:
  # required
  host: ''
  # required
  name: ''
  port: 27017
  collection: 'requests'
  username: ''
  password: ''

ipfs:
  #required
  host: ''
  port: 5001
  timeout: 3000

pubsub:
  # required
  credentialsSecretName: ''
  credentialsFileName: credentials.json
  # optional, defaults to api-sync-subscription
  # subscription:

node:
  # required
  live: ''
  # required
  test: ''

replicas: 1
resources: {}
